enum IconName {
    // 系统
    Plus = 'plus',
    CirclePlus = 'circle-plus',
    CirclePlusFilled = 'circle-plus-filled',
    Minus = 'minus',
    CircleMinus = 'circle-minus',
    CircleMinusFilled = 'circle-minus-filled',
    MinusBold = 'minus-bold',
    Search = 'search',
    Female = 'female',
    Male = 'male',
    Aim = 'aim',
    House = 'house',
    HouseFilled = 'house-filled',
    FullScreen = 'full-screen',
    Loading = 'loading',
    Link = 'link',
    Service = 'service',
    Pointer = 'pointer',
    Star = 'star',
    StarFilled = 'star-filled',
    Connection = 'connection',
    Message = 'message',
    MessageSquare = 'message-square',
    MessageSquareFilled = 'message-square-filled',
    Setting = 'setting',
    SettingFilled = 'setting-filled',
    Clock = 'clock',
    Position = 'position',
    Discount = 'discount',
    View = 'view',
    Hide = 'hide',
    Unlock = 'unlock',
    Lock = 'lock',
    Refresh = 'refresh',
    Bell = 'bell',
    Mute = 'mute',
    User = 'user',
    UserFilled = 'user-filled',
    Check = 'check',
    CircleCheck = 'circle-check',
    CircleCheckFilled = 'circle-check-filled',
    CheckBold = 'check-bold',
    Warning = 'warning',
    WarningFilled = 'warning-filled',
    WarningTriangleFilled = 'warning-triangle-filled',
    Close = 'close',
    CircleClose = 'circle-close',
    CircleCloseFilled = 'circle-close-filled',
    CloseBold = 'close-bold',
    PieChart = 'pie-chart',
    BarChart = 'bar-chart',
    More = 'more',
    MoreFilled = 'more-filled',
    Compass = 'compass',
    Filter = 'filter',
    Switch = 'swicth',
    Pen = 'pen',
    Edit = 'edit',
    Mail = 'mail',
    Finished = 'finished',
    Trash = 'trash',
    TrashFilled = 'trash-filled',
    Crop = 'crop',
    Power = 'power',
    Operation = 'operation',
    ZoomOut = 'zoom-out',
    ZoomIn = 'zoom-in',
    Info = 'info',
    InfoFilled = 'info-filled',
    QuestionFilled = 'question-filled',
    Menu = 'menu',
    UploadFilled = 'upload-filled',
    Upload = 'upload',
    Avatar = 'avatar',
    HelpFilled = 'help-filled',
    Share = 'share',
    Grid = 'grid',

    // 箭头
    ArrowLeft = 'arrow-left',
    ArrowRight = 'arrow-right',
    ArrowUp = 'arrow-up',
    ArrowDown = 'arrow-down',
    ArrowLeftBold = 'arrow-left-bold',
    ArrowRightBold = 'arrow-right-bold',
    ArrowUpBold = 'arrow-up-bold',
    ArrowDownBold = 'arrow-down-bold',
    DoubleArrowLeft = 'double-arrow-left',
    DoubleArrowRight = 'double-arrow-right',
    DoubleArrowUp = 'double-arrow-up',
    DoubleArrowDown = 'double-arrow-down',
    DownloadArrow = 'download-arrow',
    UploadArrow = 'upload-arrow',
    Top = 'top',
    Bottom = 'bottom',
    Left = 'left',
    Right = 'right',
    TopRight = 'top-right',
    TopLeft = 'top-left',
    BottomLeft = 'bottom-left',
    BottomRight = 'bottom-right',
    Sort = 'sort',
    Ascent = 'ascent',
    Descent = 'descent',
    Rank = 'rank',
    CaretLeft = 'caret-left',
    CaretRight = 'caret-right',
    CaretUp = 'caret-up',
    CaretDown = 'caret-down',
    DoubleCaret = 'double-caret',
    Expand = 'expand',
    Fold = 'fold',
    Heart = 'heart',
    HeartFilled = 'heart-filled',

    // 天气
    Sunrize = 'sunrize',
    Sunny = 'sunny',
    Ship = 'ship',
    Cloudy = 'cloudy',
    Sunset = 'sunset',
    Pouring = 'pouring',
    Moon = 'moon',
    MoonNight = 'moon-night',
    Lightning = 'lightning',

    // 文档
    DocAdd = 'doc-add',
    Doc = 'doc',
    Copy = 'copy',
    FolderOpened = 'folder-open',
    Folder = 'folder',
    FolderAdd = 'folder-add',
    Reading = 'reading',
    DocChecked = 'doc-checked',
    Collection = 'collection',

    // 媒体
    Microphone = 'microphone',
    Picture = 'picture',
    PictureFilled = 'picture-filled',
    Camera = 'camera',

    // 工具
    Calendar = 'calendar',
    MagicStick = 'magic-stick',
    Scissor = 'scissor',
    Tag = 'tag',
    Bubble = 'bubble',
    Flag = 'flag',
    Key = 'key'
}

const iconDict: Record<IconName, string> = {
    // 系统图标
    [IconName.Plus]: 'i-material-symbols:add',
    [IconName.CirclePlus]: 'i-material-symbols:add-circle-outline-rounded',
    [IconName.CirclePlusFilled]: 'i-material-symbols:add-circle-rounded',
    [IconName.Minus]: 'i-material-symbols:remove-rounded',
    [IconName.CircleMinus]: 'i-ic:round-remove-circle-outline',
    [IconName.CircleMinusFilled]: 'i-ic:round-remove-circle',
    [IconName.MinusBold]: 'i-fluent-emoji-high-contrast:minus',
    [IconName.Search]: 'i-bx:search-alt',
    [IconName.Female]: 'i-material-symbols:female-rounded',
    [IconName.Male]: 'i-material-symbols:male-rounded',
    [IconName.Aim]: 'i-icon-park-solid:aiming',
    [IconName.House]: 'i-material-symbols:house-outline-rounded',
    [IconName.HouseFilled]: 'i-material-symbols:house-rounded',
    [IconName.FullScreen]: 'i-material-symbols:fullscreen-rounded',
    [IconName.Loading]: 'i-eos-icons:loading',
    [IconName.Link]: 'i-material-symbols:link-rounded',
    [IconName.Service]: 'i-material-symbols:service-toolbox-outline-rounded',
    [IconName.Pointer]: 'i-lucide:pointer',
    [IconName.Star]: 'i-material-symbols:star-outline-rounded',
    [IconName.StarFilled]: 'i-material-symbols:star-rate-rounded',
    [IconName.Connection]: 'i-gravity-ui:plug-connection',
    [IconName.Message]: 'i-hugeicons:message-02',
    [IconName.MessageSquare]: 'i-material-symbols:chat-bubble-outline-rounded',
    [IconName.MessageSquareFilled]: 'i-material-symbols:chat-bubble-rounded',
    [IconName.Clock]: 'i-material-symbols:alarm-outline-rounded',
    [IconName.Position]: 'i-iconamoon:location',
    [IconName.Discount]: 'i-ep:discount',
    [IconName.View]: 'i-lets-icons:view',
    [IconName.Hide]: 'i-lets-icons:view-hide-light',
    [IconName.Unlock]: 'i-humbleicons:lock-open',
    [IconName.Lock]: 'i-humbleicons:lock',
    [IconName.Refresh]: 'i-material-symbols:refresh-rounded',
    [IconName.Bell]: 'i-material-symbols:notifications-outline-rounded',
    [IconName.Mute]: 'i-ci:volume-off-02',
    [IconName.User]: 'i-material-symbols:account-circle-outline',
    [IconName.UserFilled]: 'i-material-symbols:account-circle-outline',
    [IconName.Check]: 'i-material-symbols:check-small-rounded',
    [IconName.CircleCheck]: 'i-material-symbols:check-circle-outline-rounded',
    [IconName.CircleCheckFilled]: 'i-material-symbols:check-circle-rounded',
    [IconName.CheckBold]: 'i-mingcute:check-2-fill',
    [IconName.Warning]: 'i-mingcute:warning-line',
    [IconName.WarningFilled]: 'i-mingcute:warning-fill',
    [IconName.WarningTriangleFilled]: 'i-material-symbols-light:warning-rounded',
    [IconName.Close]: 'i-material-symbols:close-small-rounded',
    [IconName.CircleClose]: 'i-material-symbols:cancel-outline-rounded',
    [IconName.CircleCloseFilled]: 'i-material-symbols:cancel-rounded',
    [IconName.CloseBold]: 'i-ion:close-round',
    [IconName.PieChart]: 'i-ix:piechart',
    [IconName.BarChart]: 'i-ix:barchart',
    [IconName.More]: 'i-material-symbols:more-horiz',
    [IconName.MoreFilled]: 'i-mingcute:more-3-fill',
    [IconName.Compass]: 'i-material-symbols:compass-calibration-outline-rounded',
    [IconName.Filter]: 'i-material-symbols:filter-alt-outline',
    [IconName.Pen]: 'i-material-symbols:edit-outline-rounded',
    [IconName.Edit]: 'i-material-symbols:edit-note-outline-rounded',
    [IconName.Mail]: 'i-material-symbols:mail-outline-rounded',
    [IconName.Crop]: 'i-material-symbols:crop',
    [IconName.Power]: 'i-material-symbols:power-plug-rounded',
    [IconName.ZoomOut]: 'i-material-symbols:pinch-zoom-out-outline-rounded',
    [IconName.ZoomIn]: 'i-material-symbols:pinch-zoom-in-outline-rounded',
    [IconName.QuestionFilled]: 'i-material-symbols:help-rounded',
    [IconName.Menu]: 'i-material-symbols:menu',
    [IconName.Avatar]: 'i-material-symbols:e911-avatar-outline-rounded',
    [IconName.Share]: 'i-material-symbols:emergency-share-outline-rounded',
    [IconName.Grid]: 'i-material-symbols:grid-view-outline-rounded',
    [IconName.HelpFilled]: 'i-material-symbols:support-agent-rounded',
    [IconName.Upload]: 'i-material-symbols:drive-folder-upload-outline-rounded',
    [IconName.UploadFilled]: 'i-material-symbols:drive-folder-upload-rounded',
    [IconName.Setting]: 'i-material-symbols:settings-outline-rounded',
    [IconName.SettingFilled]: 'i-material-symbols:settings-rounded',
    [IconName.Info]: 'i-material-symbols:info-outline',
    [IconName.InfoFilled]: 'i-material-symbols:info',
    [IconName.Trash]: 'i-material-symbols:delete-outline-sharp',
    [IconName.TrashFilled]: 'i-material-symbols:delete-sharp',
    [IconName.Finished]: 'i-material-symbols:playlist-add-check-rounded',
    [IconName.Operation]: 'i-ep:operation',
    [IconName.Switch]: 'i-mi:switch',
    [IconName.Heart]: 'i-material-symbols:favorite-outline',
    [IconName.HeartFilled]: 'i-material-symbols-light-favorite-rounded'
}

export {
    iconDict, IconName
};
