enum IconName {
    Plus = 'plus',
    CirclePlus = 'circle-plus',
    CirclePlusFilled = 'circle-plus-filled',
    Minus = 'minus',
    CircleMinus = 'circle-minus',
    CircleMinusFilled = 'circle-minus-filled',
    MinusBold = 'minus-bold',
    Search = 'search',
    Female = 'female',
    Male = 'male',
    Aim = 'aim',
    House = 'house',
    HouseFilled = 'house-filled',
    FullScreen = 'full-screen',
    Loading = 'loading',
    Link = 'link',
    Service = 'service',
    Pointer = 'pointer',
    Star = 'star',
    StarFilled = 'star-filled',
    Connection = 'connection',
    Message = 'message',
    MessageSquare = 'message-square',
    MessageSquareFilled = 'message-square-filled',
    Setting = 'setting',
    SettingFilled = 'setting-filled',
    Clock = 'clock',
    Position = 'position',
    Discount = 'discount',
    View = 'view',
    Hide = 'hide',
    Unlock = 'unlock',
    Lock = 'lock',
    Refresh = 'refresh',
    Bell = 'bell',
    Mute = 'mute',
    User = 'user',
    UserFilled = 'user-filled',
    Check = 'check',
    CircleCheck = 'circle-check',
    CircleCheckFilled = 'circle-check-filled',
    CheckBold = 'check-bold',
    Warning = 'warning',
    WarningFilled = 'warning-filled',
    WarningTriangleFilled = 'warning-triangle-filled',
    Close = 'close',
    CircleClose = 'circle-close',
    CircleCloseFilled = 'circle-close-filled',
    CloseBold = 'close-bold',
    PieChart = 'pie-chart',
    BarChart = 'bar-chart',
    More = 'more',
    MoreFilled = 'more-filled',
    Compass = 'compass',
    Filter = 'filter',
    Switch = 'swicth',
    Pen = 'pen',
    Edit = 'edit',
    Mail = 'mail',
    Finished = 'finished',
    Trash = 'trash',
    TrashFilled = 'trash-filled',
    Crop = 'crop',
    Power = 'power',
    Operation = 'operation',
    ZoomOut = 'zoom-out',
    ZoomIn = 'zoom-in',
    Info = 'info',
    InfoFilled = 'info-filled',
    QuestionFilled = 'question-filled',
    Menu = 'menu',
    UploadFilled = 'upload-filled',
    Upload = 'upload',
    Avatar = 'avatar',
    HelpFilled = 'help-filled',
    Share = 'share',
    Grid = 'grid',
}

interface SnIconProps {
    name: IconName
    size: number | string
    color: string
}

export {
    IconName,
    SnIconProps
};
